sudo: false
language: ruby

install: 'gem install bundler; bundle install --retry=3'
script: 'ruby -vr bundler/setup -S rake test'

rvm:
  - 2.3
  - 2.4
  - ruby-head
  - jruby
  - rbx

matrix:
  allow_failures:
    - rvm: rbx

env:
  global:
    - JRUBY_OPTS=--debug
  matrix:
    - PORK=1
    - RSPEC=1
