sudo: false
language: ruby

install: 'gem install bundler; bundle install --retry=3'
script: 'ruby -vr bundler/setup -S rake test'

rvm:
  - 2.4
  - 2.5
  - 2.6
  - ruby-head
  - jruby

env:
  global:
    - JRUBY_OPTS=--debug
  matrix:
    - PORK=1
    - RSPEC=1
